/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_yang_opencvdemo_JavaActivity */

#ifndef _Included_com_example_yang_opencvdemo_JavaActivity
#define _Included_com_example_yang_opencvdemo_JavaActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_yang_opencvdemo_JavaActivity
 * Method:    grayProc
 * Signature: ([III)[I
 */
JNIEXPORT jintArray JNICALL Java_com_example_yang_opencvdemo_JavaActivity_grayProc
  (JNIEnv *, jclass, jintArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
